version: 2

models:
    - name: prod_aws_spot_catalog
      description: "{{ doc('aws_catalog') }}"
      tests:
      - unique:
          column_name: "(time_stamp || '-' || prod_desc || '-' || az)"
      columns:
          - name: time_stamp
            description: "The primary key for this table"
            tests:
                - not_null
    
    - name: prod_azure_spot_catalog
      description: "{{ doc('azure_catalog') }}"
      tests:
      - unique:
          column_name: "(time_stamp || '-' || prod_desc || '-' || az)"
      columns:
          - name: time_stamp
            description: "The primary key for this table"
            tests:
                - not_null

    - name: prod_spot_price_catalog
      description: "{{ doc('spot_catalog') }}"
      tests:
      - unique:
          column_name: "(time_stamp || '-' || prod_desc || '-' || az)"
      columns:
          - name: time_stamp
            description: "The primary key for this table"
            tests:
                - not_null
