name: 'Terraform-Destroy'

on:
 workflow_dispatch:
    inputs:
      name:
        description: Name of the  module
        required: true
        default: 'ec2'
        type: string
        
permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash
        working-directory: infra/${{ github.event.inputs.name }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
        
    - name: Configure AWS Credentials Action For GitHub Actions
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1 

    - name: Terraform Init
      run: | 
       touch secrets.tfvars
       echo 'redshift_password="${{ secrets.REDSHIFT_PASSWORD }}"' >> secrets.tfvars
       echo 'my_ip_address="${{ secrets.MY_IP_ADDRESS }}"' >> secrets.tfvars
       terraform init

    - name: Terraform Destroy
      run: |
       touch capstone_kp.pub
       echo '${{ secrets.CAPSTONE_PUBLIC_KEY }}' >> capstone_kp.pub
       terraform destroy -var-file secrets.tfvars --auto-approve

